project:
  type: website
  output-dir: docs

website:
  title: "Simon Tait"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Publications
        href: publications.qmd
format:
  html:
    theme: cosmo
    toc: true
    css:  styles.css

  